### ISSUE TITLE
Please clarify license

### ISSUE THREAD

**Issue by Screwland** [mattn/gopher#4]
Hi mattn

According to this page(https://golang.org/doc/gopher/README),
Gopher's image file is released under a Creative Commons 3.0 Attribution license.

So you should write license link(https://creativecommons.org/licenses/by/3.0/) in README.md or other file.

OR

Add license(CC BY 3.0) file to gopher/cmd/gopher/data
# 

In addition, you release source code under the MIT License.
But you didn't include MIT License file.
MIT has used many licenses for software, this license notice lead to misreading.
See http://www.gnu.org/licenses/license-list.html#X11License
I hope you add License file to top directory.

**Comment by Screwland** [comment]
Good.
I love Gopher.

**Comment by mattn** [comment]
me too. thanks.
